### ISSUE TITLE
JS 快速开始 demo 在手机端浏览器测试，无画面，不提示需要手机摄像头，请问为什么？

### ISSUE THREAD

**Issue by dingyiming** [itolfh/wilddog-video-quickstart#1]
JS 快速开始 demo 在手机端浏览器测试，无画面，不提示需要手机摄像头，请问为什么？

**Comment by itolfh** [comment]
你好，js video 是基于 webrtc的，目前支持webrtc 的浏览器包括chrome firefox opera。我只测试过这几种浏览器，出现你这种情况有几种可能：
1. 一些国内浏览器号称支持webrtc，但并没有进行测试和适配，可能有兼容性问题。
2. iOS操作系统中，浏览器都是基于iOS safari开发的，比如iOS 上的chrome浏览器，是不支持webrtc的，建议使用iOS sdk 而不是js sdk。 
3. android操作系统中，android 低版本也是不支持webrtc的，一般是建议android 5.1以上。否则还是用android sdk比较好。

可以通过http://caniuse.com/#search=webrtc 来查看支持情况。

**Comment by itolfh** [comment]
另外，这个项目已经不再维护，可以在https://github.com/WildDogTeam/video-quickstart-web
上看最新的quickstart。

**Comment by dingyiming** [comment]
哦，甚是感谢，
